# Generated by Django 4.0.3 on 2022-03-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
